// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbva5I2jqihbxE8xo8MbGpzOw8E3s3Hmw',
    appId: '1:457820125990:web:d0bbe7fd6e8e4cf3f0dfe7',
    messagingSenderId: '457820125990',
    projectId: 'foodapp2-bd3f5',
    authDomain: 'foodapp2-bd3f5.firebaseapp.com',
    storageBucket: 'foodapp2-bd3f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgAIkPkvapDaIF48b2n7bQsOI3guH4HU',
    appId: '1:457820125990:android:4e78d280d1371320f0dfe7',
    messagingSenderId: '457820125990',
    projectId: 'foodapp2-bd3f5',
    storageBucket: 'foodapp2-bd3f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWErjOsTfwwNB2H_PsOqnuvr5fVUGndSY',
    appId: '1:457820125990:ios:4d10eb5d586868b5f0dfe7',
    messagingSenderId: '457820125990',
    projectId: 'foodapp2-bd3f5',
    storageBucket: 'foodapp2-bd3f5.appspot.com',
    iosBundleId: 'com.example.appfood2',
  );
}
